<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Drips :: Debugger</title>
    <!-- jQuery -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <!-- Highlight.js -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.2.0/styles/github-gist.min.css"/>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.2.0/highlight.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('pre code').each(function (i, block) {
                hljs.highlightBlock(block);
            });
        });
    </script>
    <style>
        @import url(https://fonts.googleapis.com/css?family=Maven+Pro);

        body {
            margin: 0;
            padding: 0 10px;
            font-family: 'Maven Pro', sans-serif;
            background-color: #434a54;
        }

        header {
            margin-top: 15px;
        }

        #logo img {
            height: 70px;
        }

        .exception {
            margin: 15px 0;
        }

        .exception-title {
            background-color: #e9573f;
            color: white;
            padding: 10px;
            margin: 0;
        }

        .exception-code {
            margin-top: -13px;
            margin-bottom: -13px;
        }

        .exception-file-info {
            display: block;
            padding: 10px;
            font-size: 10px;
            background-color: #353535;
            color: #bebebe;
            margin: 0;
        }

        .highlight {
            background-color: #e9573f;
            padding: 2px 0 1px 0;
            display: block;
            margin-bottom: -14px;
        }

        .highlight *, .highlight {
            color: white;
        }

        .stacktrace {
            display: none;
            margin: 20px;
            color: white;
        }

        .stacktrace p {
            font-family: monospace;
            margin: 0;
            font-size: 12px;
            line-height: 18px;
            color: #bebebe;
        }

        .stacktrace p > strong {
            color: white;
        }
        
        .exception:active .stacktrace {
            display: block;
        }

        #copyright {
            padding: 25px;
            text-align: center;
            color: #bebebe;
        }

        #copyright a {
            color: #bebebe;
        }
    </style>
</head>
<body>
    <header>
        <div id="logo">
            <?php include(DRIPS_DIRECTORY . '/bootstrap/setup/logo.php'); ?>
        </div>
    </header>

    <section class="exception">
        <h2 class="exception-title">[<?= $e->getClass(); ?>] <?= $e->getMessage(); ?></h2>

        <div class="exception-code">
            <?= getCode($e->getFile(), $e->getLine()); ?>
        </div>
        <small class="exception-file-info"><?= $e->getFile() ?>:<?= $e->getLine(); ?></small>

        <div class="stacktrace">
            <h3>Stacktrace:</h3>
            <?php foreach ($e->getTrace() as $trace): ?>
                <p><?= $trace['file'] ?>: <strong><?= $trace['class'] . $trace['type'] . $trace['function'] ?></strong></p>
            <?php endforeach; ?>
        </div>
    </section>

    <footer id="copyright">
        Copyright &copy; <a href="http://prowect.com" target="_blank">Prowect</a>
    </footer>
</body>
</html>
<?php

function getCode($path, $line)
{
    $snippet = 7;
    $code = str_replace('>', '&gt', str_replace('<', '&lt;', file_get_contents($path)));
    $codesplit = explode("\n", $code);
    $lines = count($codesplit);
    $from = $line < $snippet ? 0 : $line - $snippet;
    $to = $lines < $line + $snippet ? $lines + 1 : $line + $snippet;
    $new = array();
    for ($i = $from; $i < $to - 1; $i++) {
        if ($i + 1 == $line) {
            $new[] = '<span class="highlight">' . ($i + 1) . ' ' . $codesplit[$i] . '</span>';
        } else {
            $new[] = ($i + 1) . ' ' . $codesplit[$i];
        }
    }

    return '<pre><code>' . implode("\n", $new) . "\n</code></pre>";
}

?>